#!/bin/bash
################################################################################
#
# GLOBAL VARS
#
################################################################################

export QAA_PATH=$(pwd)
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}${QAA_PATH}/tools/lib
export PYTHONPATH=${PYTHONPATH:+$PYTHONPATH:}${QAA_PATH}/lib:${QAA_PATH}/tools/python

BRANCH=$1

echo creating a branch called ${BRANCH} from master
time git branch -a | grep ${BRANCH}
time git checkout master
time git pull --rebase
time git pull --rebase upstream master
time git checkout -b ${BRANCH}
time git push
time git branch --set-upstream-to=origin/${BRANCH} ${BRANCH}
time git pull
