MMIX_HOME=~/mmix

MMIX_PROG=test

$MMIX_HOME/mmixal-2 $MMIX_HOME/$MMIX_PROG.mms
$MMIX_HOME/mmix-2 $MMIX_HOME/$MMIX_PROG.mmo
# $MMIX_HOME/mmmix-2 $MMIX_HOME/$MMIX_PROG.mmconfig $MMIX_HOME/$MMIX_PROG.mmo
# $MMIX_HOME/mmmix-2 $MMIX_HOME/$MMIX_PROG.mmconfig $MMIX_HOME/$MMIX_PROG.mms
$MMIX_HOME/mmmix-2 $MMIX_HOME/$MMIX_PROG.mmconfig $MMIX_HOME/$MMIX_PROG.mmix
