(define (count-change amount)
    (cc amount 5))

(define (cc amount kinds-of-coins)
    (cond ((= amount 0) 1)
        ((or (< amount 0) (= kinds-of-coins 0)) 0)
        (else (+ (cc amount
                (- kinds-of-coins 1))
            (cc (- amount
                (first-denomination kinds-of-coins))
                kinds-of-coins)))))

(define (first-denomination kinds-of-coins)
    (cond ((= kinds-of-coins 1) 1)
        ((= kinds-of-coins 2) 5)
        ((= kinds-of-coins 3) 10)
        ((= kinds-of-coins 4) 25)
        ((= kinds-of-coins 5) 50)))

(display "\n")
(display "\n")
(display "count-change 100\n")
(display (count-change 100))
(display "\n")
(display "count-change 1\n")
(display (count-change 1))
(display "\n")
(display "count-change 4\n")
(display (count-change 4))
(display "\n")
(display "count-change 5\n")
(display (count-change 5))
(display "\n")
(display "count-change 6\n")
(display (count-change 6))
(display "\n")
(display "count-change 9\n")
(display (count-change 9))
(display "\n")
(display "count-change 10\n")
(display (count-change 10))
(display "\n")
(display "count-change 14\n")
(display (count-change 14))
(display "\n")
(display "count-change 15\n")
(display (count-change 15))
(display "\n")
(display "count-change 19\n")
(display (count-change 19))
(display "\n")
(display "count-change 20\n")
(display (count-change 20))
(display "\n")
(display "count-change 24\n")
(display (count-change 24))
(display "\n")
(display "count-change 25\n")
(display (count-change 25))
(display "\n")
(display "count-change 29\n")
(display (count-change 29))
(display "\n")
(display "count-change 30\n")
(display (count-change 30))
(display "\n")
(display "count-change 34\n")
(display (count-change 34))
(display "\n")
(display "count-change 35\n")
(display (count-change 35))
(display "\n")
(display "count-change 39\n")
(display (count-change 39))
(display "\n")
(display "count-change 40\n")
(display (count-change 40))
(display "\n")
(display "count-change 44\n")
(display (count-change 44))
(display "\n")
(display "count-change 45\n")
(display (count-change 45))
(display "\n")
(display "count-change 49\n")
(display (count-change 49))
(display "\n")
(display "count-change 50\n")
(display (count-change 50))

(display "\n")
(display "count-change 99\n")
(display (count-change 99))
(display "\n")
(exit)
