go run $GOPATH/src/github.com/jtraver/hello/hello.go
go run $GOPATH/src/gopl.io/ch1/dup1/main.go
go run $GOPATH/src/gopl.io/ch1/dup2/main.go
go run $GOPATH/src/gopl.io/ch1/dup3/main.go
go run $GOPATH/src/gopl.io/ch1/echo1/main.go
go run $GOPATH/src/gopl.io/ch1/echo2/main.go
go run $GOPATH/src/gopl.io/ch1/echo3/main.go
go run $GOPATH/src/gopl.io/ch1/fetch/main.go
go run $GOPATH/src/gopl.io/ch1/fetchall/main.go
go run $GOPATH/src/gopl.io/ch1/helloworld/main.go
go run $GOPATH/src/gopl.io/ch1/lissajous/main.go
go run $GOPATH/src/gopl.io/ch1/server1/main.go
go run $GOPATH/src/gopl.io/ch1/server2/main.go
go run $GOPATH/src/gopl.io/ch1/server3/main.go
go run $GOPATH/src/gopl.io/ch10/cross/main.go
go run $GOPATH/src/gopl.io/ch10/jpeg/main.go
go run $GOPATH/src/gopl.io/ch11/echo/echo.go
go run $GOPATH/src/gopl.io/ch11/echo/echo_test.go
go run $GOPATH/src/gopl.io/ch11/storage1/storage.go
go run $GOPATH/src/gopl.io/ch11/storage2/quota_test.go
go run $GOPATH/src/gopl.io/ch11/storage2/storage.go
go run $GOPATH/src/gopl.io/ch11/word1/word.go
go run $GOPATH/src/gopl.io/ch11/word1/word_test.go
go run $GOPATH/src/gopl.io/ch11/word2/word.go
go run $GOPATH/src/gopl.io/ch11/word2/word_test.go
go run $GOPATH/src/gopl.io/ch12/display/display.go
go run $GOPATH/src/gopl.io/ch12/display/display_test.go
go run $GOPATH/src/gopl.io/ch12/format/format.go
go run $GOPATH/src/gopl.io/ch12/format/format_test.go
go run $GOPATH/src/gopl.io/ch12/methods/methods.go
go run $GOPATH/src/gopl.io/ch12/methods/methods_test.go
go run $GOPATH/src/gopl.io/ch12/params/params.go
go run $GOPATH/src/gopl.io/ch12/search/main.go
go run $GOPATH/src/gopl.io/ch12/sexpr/decode.go
go run $GOPATH/src/gopl.io/ch12/sexpr/encode.go
go run $GOPATH/src/gopl.io/ch12/sexpr/pretty.go
go run $GOPATH/src/gopl.io/ch12/sexpr/sexpr_test.go
go run $GOPATH/src/gopl.io/ch13/bzip/bzip2.go
go run $GOPATH/src/gopl.io/ch13/bzip/bzip2_test.go
go run $GOPATH/src/gopl.io/ch13/bzip-print/bzip2.go
go run $GOPATH/src/gopl.io/ch13/bzip-print/bzip2_test.go
go run $GOPATH/src/gopl.io/ch13/bzipper/main.go
go run $GOPATH/src/gopl.io/ch13/equal/equal.go
go run $GOPATH/src/gopl.io/ch13/equal/equal_test.go
go run $GOPATH/src/gopl.io/ch13/unsafeptr/main.go
go run $GOPATH/src/gopl.io/ch2/boiling/main.go
go run $GOPATH/src/gopl.io/ch2/cf/main.go
go run $GOPATH/src/gopl.io/ch2/echo4/main.go
go run $GOPATH/src/gopl.io/ch2/ftoc/main.go
go run $GOPATH/src/gopl.io/ch2/popcount/main.go
go run $GOPATH/src/gopl.io/ch2/popcount/popcount_test.go
go run $GOPATH/src/gopl.io/ch2/tempconv/conv.go
go run $GOPATH/src/gopl.io/ch2/tempconv/tempconv.go
go run $GOPATH/src/gopl.io/ch2/tempconv0/celsius.go
go run $GOPATH/src/gopl.io/ch2/tempconv0/tempconv_test.go
go run $GOPATH/src/gopl.io/ch3/basename1/main.go
go run $GOPATH/src/gopl.io/ch3/basename2/main.go
go run $GOPATH/src/gopl.io/ch3/comma/main.go
go run $GOPATH/src/gopl.io/ch3/mandelbrot/main.go
go run $GOPATH/src/gopl.io/ch3/netflag/netflag.go
go run $GOPATH/src/gopl.io/ch3/printints/main.go
go run $GOPATH/src/gopl.io/ch3/surface/main.go
go run $GOPATH/src/gopl.io/ch4/append/main.go
go run $GOPATH/src/gopl.io/ch4/autoescape/main.go
go run $GOPATH/src/gopl.io/ch4/charcount/main.go
go run $GOPATH/src/gopl.io/ch4/dedup/main.go
go run $GOPATH/src/gopl.io/ch4/embed/main.go
go run $GOPATH/src/gopl.io/ch4/github/github.go
go run $GOPATH/src/gopl.io/ch4/github/search.go
go run $GOPATH/src/gopl.io/ch4/graph/main.go
go run $GOPATH/src/gopl.io/ch4/issues/main.go
go run $GOPATH/src/gopl.io/ch4/issueshtml/main.go
go run $GOPATH/src/gopl.io/ch4/issuesreport/main.go
go run $GOPATH/src/gopl.io/ch4/movie/main.go
go run $GOPATH/src/gopl.io/ch4/nonempty/main.go
go run $GOPATH/src/gopl.io/ch4/rev/main.go
go run $GOPATH/src/gopl.io/ch4/sha256/main.go
go run $GOPATH/src/gopl.io/ch4/treesort/sort.go
go run $GOPATH/src/gopl.io/ch4/treesort/sort_test.go
go run $GOPATH/src/gopl.io/ch5/defer1/defer.go
go run $GOPATH/src/gopl.io/ch5/defer2/defer.go
go run $GOPATH/src/gopl.io/ch5/fetch/main.go
go run $GOPATH/src/gopl.io/ch5/findlinks1/main.go
go run $GOPATH/src/gopl.io/ch5/findlinks2/main.go
go run $GOPATH/src/gopl.io/ch5/findlinks3/findlinks.go
go run $GOPATH/src/gopl.io/ch5/links/links.go
go run $GOPATH/src/gopl.io/ch5/outline/main.go
go run $GOPATH/src/gopl.io/ch5/outline2/outline.go
go run $GOPATH/src/gopl.io/ch5/squares/main.go
go run $GOPATH/src/gopl.io/ch5/sum/main.go
go run $GOPATH/src/gopl.io/ch5/title1/title.go
go run $GOPATH/src/gopl.io/ch5/title2/title.go
go run $GOPATH/src/gopl.io/ch5/title3/title.go
go run $GOPATH/src/gopl.io/ch5/toposort/main.go
go run $GOPATH/src/gopl.io/ch5/trace/main.go
go run $GOPATH/src/gopl.io/ch5/wait/wait.go
go run $GOPATH/src/gopl.io/ch6/coloredpoint/main.go
go run $GOPATH/src/gopl.io/ch6/geometry/geometry.go
go run $GOPATH/src/gopl.io/ch6/intset/intset.go
go run $GOPATH/src/gopl.io/ch6/intset/intset_test.go
go run $GOPATH/src/gopl.io/ch6/urlvalues/main.go
go run $GOPATH/src/gopl.io/ch7/bytecounter/main.go
go run $GOPATH/src/gopl.io/ch7/eval/ast.go
go run $GOPATH/src/gopl.io/ch7/eval/check.go
go run $GOPATH/src/gopl.io/ch7/eval/coverage_test.go
go run $GOPATH/src/gopl.io/ch7/eval/eval.go
go run $GOPATH/src/gopl.io/ch7/eval/eval_test.go
go run $GOPATH/src/gopl.io/ch7/eval/parse.go
go run $GOPATH/src/gopl.io/ch7/eval/print.go
go run $GOPATH/src/gopl.io/ch7/http1/main.go
go run $GOPATH/src/gopl.io/ch7/http2/main.go
go run $GOPATH/src/gopl.io/ch7/http3/main.go
go run $GOPATH/src/gopl.io/ch7/http3a/main.go
go run $GOPATH/src/gopl.io/ch7/http4/main.go
go run $GOPATH/src/gopl.io/ch7/sleep/sleep.go
go run $GOPATH/src/gopl.io/ch7/sorting/main.go
go run $GOPATH/src/gopl.io/ch7/surface/surface.go
go run $GOPATH/src/gopl.io/ch7/tempconv/tempconv.go
go run $GOPATH/src/gopl.io/ch7/tempflag/tempflag.go
go run $GOPATH/src/gopl.io/ch7/xmlselect/main.go
go run $GOPATH/src/gopl.io/ch8/cake/cake.go
go run $GOPATH/src/gopl.io/ch8/cake/cake_test.go
go run $GOPATH/src/gopl.io/ch8/chat/chat.go
go run $GOPATH/src/gopl.io/ch8/clock1/clock.go
go run $GOPATH/src/gopl.io/ch8/clock2/clock.go
go run $GOPATH/src/gopl.io/ch8/countdown1/countdown.go
go run $GOPATH/src/gopl.io/ch8/countdown2/countdown.go
go run $GOPATH/src/gopl.io/ch8/countdown3/countdown.go
go run $GOPATH/src/gopl.io/ch8/crawl1/findlinks.go
go run $GOPATH/src/gopl.io/ch8/crawl2/findlinks.go
go run $GOPATH/src/gopl.io/ch8/crawl3/findlinks.go
go run $GOPATH/src/gopl.io/ch8/du1/main.go
go run $GOPATH/src/gopl.io/ch8/du2/main.go
go run $GOPATH/src/gopl.io/ch8/du3/main.go
go run $GOPATH/src/gopl.io/ch8/du4/main.go
go run $GOPATH/src/gopl.io/ch8/netcat1/netcat.go
go run $GOPATH/src/gopl.io/ch8/netcat2/netcat.go
go run $GOPATH/src/gopl.io/ch8/netcat3/netcat.go
go run $GOPATH/src/gopl.io/ch8/pipeline1/main.go
go run $GOPATH/src/gopl.io/ch8/pipeline2/main.go
go run $GOPATH/src/gopl.io/ch8/pipeline3/main.go
go run $GOPATH/src/gopl.io/ch8/reverb1/reverb.go
go run $GOPATH/src/gopl.io/ch8/reverb2/reverb.go
go run $GOPATH/src/gopl.io/ch8/spinner/main.go
go run $GOPATH/src/gopl.io/ch8/thumbnail/main.go
go run $GOPATH/src/gopl.io/ch8/thumbnail/thumbnail.go
go run $GOPATH/src/gopl.io/ch8/thumbnail/thumbnail_test.go
go run $GOPATH/src/gopl.io/ch9/bank1/bank.go
go run $GOPATH/src/gopl.io/ch9/bank1/bank_test.go
go run $GOPATH/src/gopl.io/ch9/bank2/bank.go
go run $GOPATH/src/gopl.io/ch9/bank2/bank_test.go
go run $GOPATH/src/gopl.io/ch9/bank3/bank.go
go run $GOPATH/src/gopl.io/ch9/bank3/bank_test.go
go run $GOPATH/src/gopl.io/ch9/memo1/memo.go
go run $GOPATH/src/gopl.io/ch9/memo1/memo_test.go
go run $GOPATH/src/gopl.io/ch9/memo2/memo.go
go run $GOPATH/src/gopl.io/ch9/memo2/memo_test.go
go run $GOPATH/src/gopl.io/ch9/memo3/memo.go
go run $GOPATH/src/gopl.io/ch9/memo3/memo_test.go
go run $GOPATH/src/gopl.io/ch9/memo4/memo.go
go run $GOPATH/src/gopl.io/ch9/memo4/memo_test.go
go run $GOPATH/src/gopl.io/ch9/memo5/memo.go
go run $GOPATH/src/gopl.io/ch9/memo5/memo_test.go
go run $GOPATH/src/gopl.io/ch9/memotest/memotest.go
